### ISSUE TITLE
Unused ivar

### ISSUE THREAD

**Issue by x0000ff** [feliperuzg/CleanExample#3]
Looks like ivar `locator` isn't used in code:

**LoginViewController.swift:16**

```swift
fileprivate let locator = AuthenticationServiceLocator()
```

https://github.com/feliperuzg/CleanExample/blob/381f78e6113e6d69401b4be5cb2d03255d5422e6/CleanExample/Authentication/View/LoginViewController.swift#L16

**Comment by feliperuzg** [comment]
Thanks, removed on 20bc2aab5dbfa021593b4338440044de658bc870
